# Atwater Subsistence Diet Project

In [1]:
!pip install -r requirements.txt
#!pip install --upgrade pip
import pandas as pd
import numpy as np

Requirement already satisfied: Pint>=0.8.1 in /srv/app/venv/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: numpy>=1.15.0 in /srv/app/venv/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pandas>=0.23.3 in /srv/app/venv/lib/python3.6/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: requests>=2.20.0 in /srv/app/venv/lib/python3.6/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: scipy>=1.1.0 in /srv/app/venv/lib/python3.6/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: pytz>=2011k in /srv/app/venv/lib/python3.6/site-packages (from pandas>=0.23.3->-r requirements.txt (line 11))
Requirement already satisfied: python-dateutil>=2.5.0 in /srv/app/venv/lib/python3.6/site-packages (from pandas>=0.23.3->-r requirements.txt (line 11))
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /srv/app/venv/lib/python3.6/site-packages (from requests>=2.20.0->-r requirements.txt (line 15))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /srv/app/venv/lib/python3.6/site-packages (from requests>=2.20.0->-r requirements.txt (line 15))
Requirement already satisfied: idna<2.9,>=2.5 in /srv/app/venv/lib/python3.6/site-packages (from requests>=2.20.0->-r requirements.txt (line 15))
Requirement already satisfied: certifi>=2017.4.17 in /srv/app/venv/lib/python3.6/site-packages (from requests>=2.20.0->-r requirements.txt (line 15))
Requirement already satisfied: six>=1.5 in /srv/app/venv/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.23.3->-r requirements.txt (line 11))
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# Pulling FDC Data

In [2]:
user = "joyceml"

In [3]:
apikey = {'joyceml':"r4qly7ALQ3bhuG1rdr63aCqUZYieS69MEwaXDogb"}

### Whenever adding a new ingredient: need to 
1. pull from FDC data
2. put df name into lista, put Sheets column name into food_list
3. Fill in Google Sheets

In [4]:
#Identify Best-Fitting FDCID (choose based on description)
import fooddatacentral as fdc

df1 = fdc.search(apikey[user],"dried shitake mushrooms")
df1

,additionalDescriptions,allHighlightFields,commonNames,dataType,description,fdcId,foodCode,ndbNumber,publishedDate,scientificName,score
0,NaN,,NaN,SR Legacy,"Mushrooms, shiitake, dried",168436,NaN,11268,2019-04-01,Lentinus edodes,618.43524
1,shiitake,,NaN,Survey (FNDDS),"Mushroom, Asian, cooked, from dried",343137,75219100,NaN,2019-04-01,NaN,513.16090
2,commercially canned lowfat gravy,,NaN,Survey (FNDDS),"Gravy, mushroom",338992,28500100,NaN,2019-04-01,NaN,354.18362
3,NaN,,NaN,Survey (FNDDS),"Mushrooms, pickled",343664,75505000,NaN,2019-04-01,NaN,354.18362
4,NaN,,NaN,Survey (FNDDS),"Mushrooms, raw",342623,75115000,NaN,2019-04-01,NaN,354.18362
5,NaN,,NaN,Survey (FNDDS),"Mushrooms, stuffed",343587,75414020,NaN,2019-04-01,NaN,354.18362
6,sweetened,,NaN,Survey (FNDDS),"Blueberries, dried",341476,62105000,NaN,2019-04-01,NaN,335.97714
7,sweetened,,NaN,Survey (FNDDS),"Cherries, dried",341477,62106000,NaN,2019-04-01,NaN,335.97714
8,Craisins,,NaN,Survey (FNDDS),"Cranberries, dried",341481,62109100,NaN,2019-04-01,NaN,335.97714
9,NaN,,NaN,Survey (FNDDS),"Currants, dried",341480,62108100,NaN,2019-04-01,NaN,335.97714
10,NaN,,lychee,SR Legacy,"Litchis, dried",169087,NaN,9165,2019-04-01,NaN,335.97714
11,NaN,,NaN,SR Legacy,"Longans, dried",169907,NaN,9173,2019-04-01,NaN,335.97714
12,NaN,,NaN,Survey (FNDDS),"Mango, dried",341488,62114050,NaN,2019-04-01,NaN,335.97714
13,NaN,,NaN,Survey (FNDDS),"Octopus, dried",337872,26205170,NaN,2019-04-01,NaN,335.97714
14,NaN,,NaN,Survey (FNDDS),"Papaya, dried",341489,62114110,NaN,2019-04-01,NaN,335.97714
15,NaN,,NaN,SR Legacy,"Pepeao, dried",168418,NaN,11230,2019-04-01,NaN,335.97714
16,NaN,,NaN,Survey (FNDDS),"Pineapple, dried",341498,62120100,NaN,2019-04-01,NaN,335.97714
17,NaN,,NaN,Survey (FNDDS),"Salmon, dried",337769,26137170,NaN,2019-04-01,NaN,335.97714
18,NaN,,NaN,Survey (FNDDS),"Sardines, dried",337773,26139170,NaN,2019-04-01,NaN,335.97714
19,"sea moss, kelp; laver",,NaN,Survey (FNDDS),"Seaweed, dried",343324,75232000,NaN,2019-04-01,NaN,335.97714
20,NaN,,NaN,Survey (FNDDS),"Shrimp, dried",337958,26319170,NaN,2019-04-01,NaN,335.97714
21,NaN,,mint,SR Legacy,"Spearmint, dried",172239,NaN,2066,2019-04-01,NaN,335.97714
22,cuttlefish; calamari,,NaN,Survey (FNDDS),"Squid, dried",337885,26213170,NaN,2019-04-01,NaN,335.97714
23,sun-dried tomatoes,<b>Includes</b>: sun-<em>dried</em> tomatoes,NaN,Survey (FNDDS),"Tomatoes, red, dried",342520,74206000,NaN,2019-04-01,NaN,319.86356
24,NaN,,NaN,SR Legacy,"Gravy, mushroom, canned",171170,NaN,6121,2019-04-01,NaN,317.88528
25,NaN,,NaN,Survey (FNDDS),"Mushroom soup, NFS",343700,75607000,NaN,2019-04-01,NaN,317.88528
26,NaN,,NaN,SR Legacy,"Mushrooms, Chanterelle, raw",168422,NaN,11239,2019-04-01,Cantharellus californicus or Cantharellus ciba...,317.88528
27,NaN,,NaN,SR Legacy,"Mushrooms, enoki, raw",169382,NaN,11950,2019-04-01,Flammulina veluptipes,317.88528
28,NaN,,NaN,SR Legacy,"Mushrooms, maitake, raw",169403,NaN,11993,2019-04-01,Grifola frondosa,317.88528
29,NaN,,NaN,SR Legacy,"Mushrooms, morel, raw",168423,NaN,11240,2019-04-01,Morchella spp.,317.88528
30,NaN,,NaN,SR Legacy,"Mushrooms, oyster, raw",168580,NaN,11987,2019-04-01,Pleurotus ostreatus,317.88528
31,NaN,,Portobello,SR Legacy,"Mushrooms, portabella, grilled",169243,NaN,11243,2019-04-01,Agaricus bisporus,317.88528
32,NaN,,Portabello,SR Legacy,"Mushrooms, portabella, raw",169255,NaN,11265,2019-04-01,Agaricus bisporus,317.88528
33,NaN,,NaN,SR Legacy,"Mushrooms, shiitake, raw",169242,NaN,11238,2019-04-01,Lentinus edodes,317.88528
34,NaN,,NaN,SR Legacy,"Mushrooms, white, microwaved",169402,NaN,11992,2019-04-01,Agaricus bisporus,317.88528
35,NaN,,NaN,SR Legacy,"Mushrooms, white, raw",169251,NaN,11260,2019-04-01,Agaricus bisporus,317.88528
36,"dried diet snack, plain or flavored","<b>Includes</b>: <em>dried</em> diet snack, pl...",NaN,Survey (FNDDS),"Apple, dried, uncooked",341467,62101100,NaN,2019-04-01,NaN,316.63065
37,"dried apricot, NS as to cooked or uncooked","<b>Includes</b>: <em>dried</em> apricot, NS as...",NaN,Survey (FNDDS),"Apricot, dried, uncooked",341472,62104100,NaN,2019-04-01,NaN,316.63065
38,NaN,,NaN,SR Legacy,"Agave, dried (Southwest)",168993,NaN,35194,2019-04-01,NaN,301.54996
39,NaN,,NaN,SR Legacy,"Beef, cured, dried",170604,NaN,13350,2019-04-01,NaN,301.54996
40,NaN,,NaN,SR Legacy,"Blueberries, dried, sweetened",168158,NaN,9163,2019-04-01,NaN,301.54996
41,NaN,,NaN,SR Legacy,"Chives, freeze-dried",170075,NaN,11615,2019-04-01,NaN,301.54996
42,NaN,,NaN,Survey (FNDDS),"Cod, dried, salted",337607,26109170,NaN,2019-04-01,NaN,301.54996
43,NaN,,NaN,SR Legacy,"Corn, dried (Navajo)",167631,NaN,35134,2019-04-01,NaN,301.54996
44,NaN,,NaN,Survey (FNDDS),"Corn, dried, cooked",343002,75216070,NaN,2019-04-01,NaN,301.54996
45,NaN,,raisin,SR Legacy,"Currants, zante, dried",171724,NaN,9085,2019-04-01,Vitis vinifera,301.54996
46,NaN,,NaN,Foundation,"Egg, white, dried",323793,NaN,1173,2019-04-01,NaN,301.54996
47,NaN,,NaN,SR Legacy,"Egg, white, dried",172204,NaN,1173,2019-04-01,NaN,301.54996
48,NaN,,NaN,SR Legacy,"Egg, whole, dried",172188,NaN,1133,2019-04-01,NaN,301.54996
49,NaN,,NaN,Foundation,"Egg, whole, dried",329490,NaN,1133,2019-04-01,NaN,301.54996

In [5]:
#Pull Specific Vegetables from FDC Dataset

collard_greens = fdc.nutrients(apikey[user],fdc_id=380297).rename(columns={"Quantity": "Collard Greens", "Units": "collard_greens_u"}) #walmart
carrots = fdc.nutrients(apikey[user],fdc_id=658616).rename(columns={"Quantity": "Carrots", "Units": "carrot_u"})
cabbage = fdc.nutrients(apikey[user],fdc_id=169975).rename(columns={"Quantity": "Cabbage", "Units": "cabbage_u"})
lettuce = fdc.nutrients(apikey[user],fdc_id=342618).rename(columns={"Quantity": "Lettuce", "Units": "lettuce_u"})
cauliflower = fdc.nutrients(apikey[user],fdc_id=528384).rename(columns={"Quantity": "Cauliflower", "Units": "cauliflower_u"})
diced_tomatoes = fdc.nutrients(apikey[user],fdc_id=371622).rename(columns={"Quantity": "Diced Tomatoes", "Units": "tomatoes_u"})
rice = fdc.nutrients(apikey[user],fdc_id=450892).rename(columns={"Quantity": "Rice", "Units": "rice_u"})
#nuts = fdc.nutrients(apikey[user],fdc_id=570267).rename(columns={"Quantity": "nuts_q", "Units": "nuts_u"})
bananas = fdc.nutrients(apikey[user],fdc_id=173944).rename(columns={"Quantity": "Bananas", "Units": "bananas_u"})
tofu = fdc.nutrients(apikey[user],fdc_id=496446).rename(columns={"Quantity": "Tofu", "Units": "tofu_u"})
eggs = fdc.nutrients(apikey[user],fdc_id=442160).rename(columns={"Quantity": "Eggs", "Units": "eggs_u"})
cereal = fdc.nutrients(apikey[user],fdc_id=653426).rename(columns={"Quantity": "Cereal", "Units": "cereal_u"})
mushrooms = fdc.nutrients(apikey[user],fdc_id=168436).rename(columns={"Quantity": "Dried Shitake", "Units": "mushrooms_u"})
rice_wrap = fdc.nutrients(apikey[user],fdc_id=340211).rename(columns={"Quantity": "Rice Wrap", "Units": "rice_wrap_u"})
noodles = fdc.nutrients(apikey[user],fdc_id=373372).rename(columns={"Quantity": "Noodles", "Units": "noodles_u"})
peanut_butter = fdc.nutrients(apikey[user],fdc_id=357668).rename(columns={"Quantity": "Peanut Butter", "Units": "peanut_butter_u"})
cilantro = fdc.nutrients(apikey[user],fdc_id=530557).rename(columns={"Quantity": "Cilantro", "Units": "cilantro_u"})
cucumber = fdc.nutrients(apikey[user],fdc_id=342612).rename(columns={"Quantity": "Cucumbers", "Units": "cucumber_u"})

lista = [collard_greens, carrots, cabbage, lettuce, cauliflower, diced_tomatoes, rice, tofu, bananas, eggs, cereal, mushrooms, rice_wrap, noodles, peanut_butter, cilantro, cucumber]
food_list = ['Collard Greens', 'Carrots', 'Cabbage', 'Lettuce', 'Cauliflower', 'Diced Tomatoes', 'Rice', 'Tofu', 'Banana', 'Eggs', 'Cereal', "Dried Shitake", "Rice Wrap", "Noodles", "Peanut Butter", "Cilantro", "Cucumbers"]

In [6]:
#Matrix Manipulation

#Combine lists that are pulled from FDC Dataset
start = collard_greens.reset_index()
for i in lista[1:]:
    veg_t = start.merge(i.reset_index(), how = 'outer', on = 'index')
    start = veg_t
    

#make sure units are the same (convert kJ to kcal)
#one_kj = 0.239006 kcal
kj = veg_t['Cabbage'][3]
veg_t['Cabbage'][3] = kj*0.239006
kj = veg_t['Bananas'][3]
veg_t['Bananas'][3] = kj*0.239006
table = veg_t.set_index('index')

unit_list = list(veg_t['cabbage_u'])
unit_list[3] = "kcal"

#get rid of units columns
keep = list(np.arange(0, len(lista)*2,2))

total_table = table.iloc[:, keep]
total_table = total_table.fillna(0)
total_table['meal_total'] = total_table.sum(axis=1)
total_table['units'] = unit_list

#table with rows as type of nutrient, columns are each vegetable and a total
total_table

#export = total_table.reset_index()
D =total_table.drop(columns={'meal_total', 'units'})
D

    

#carrots.reset_index().merge(collard_greens.reset_index(), how= 'outer', on = 'index')

/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/srv/app/venv/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,Collard Greens,Carrots,Cabbage,Lettuce,Cauliflower,Diced Tomatoes,Rice,Tofu,Bananas,Eggs,Cereal,Dried Shitake,Rice Wrap,Noodles,Peanut Butter,Cilantro,Cucumbers
index,,,,,,,,,,,,,,,,,
"Calcium, Ca",78.00,38.00,40.000000,18.000,0.00,16.00,44.00,118.00,5.000000,40.00,0.000,11.000,10.000,0.00,0.00,0.0,14.000
"Carbohydrate, by difference",3.12,11.54,5.800000,2.970,4.71,7.14,80.00,3.53,22.840000,0.00,89.660,75.370,72.540,77.78,21.88,0.0,2.160
Cholesterol,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,370.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Energy,16.00,38.00,24.617618,14.000,29.00,32.00,356.00,82.00,88.671226,140.00,379.000,1238.000,329.000,370.00,625.00,0.0,12.000
"Fatty acids, total monounsaturated",0.00,0.00,0.017000,0.006,0.00,0.00,0.00,0.00,0.032000,0.00,0.000,0.317,0.376,0.00,0.00,0.0,0.002
"Fatty acids, total polyunsaturated",0.00,0.00,0.017000,0.074,0.00,0.00,0.00,0.00,0.073000,0.00,0.000,0.151,0.322,0.00,0.00,0.0,0.003
"Fatty acids, total saturated",0.00,0.00,0.034000,0.018,0.00,0.00,0.00,0.47,0.112000,3.00,0.000,0.225,0.328,0.00,10.94,0.0,0.013
"Fatty acids, total trans",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
"Fiber, total dietary",1.60,3.80,2.500000,1.200,1.20,1.60,2.20,1.20,2.600000,0.00,3.400,11.500,2.100,3.70,6.20,0.0,0.700
"Iron, Fe",0.84,1.28,0.470000,0.410,0.00,0.29,4.00,3.39,0.260000,1.44,15.520,1.720,0.380,1.33,2.25,0.0,0.220
"Potassium, K",74.00,256.00,170.000000,141.000,0.00,119.00,0.00,0.00,358.000000,0.00,121.000,1534.000,65.000,148.00,0.00,0.0,136.000
Protein,1.56,1.28,1.280000,0.900,1.18,0.79,6.67,10.59,1.090000,12.00,3.450,9.580,5.070,11.11,25.00,0.0,0.590
"Sodium, Na",12.00,64.00,18.000000,10.000,29.00,183.00,0.00,9.00,1.000000,140.00,517.000,13.000,310.000,352.00,469.00,0.0,2.000
"Sugars, total including NLEA",0.00,6.41,3.200000,1.970,2.35,1.59,0.00,0.00,12.230000,0.00,34.480,2.210,0.270,1.85,9.38,0.0,1.380
Total lipid (fat),0.00,0.00,0.100000,0.140,0.00,0.00,0.00,2.35,0.330000,10.00,0.000,0.990,1.210,1.85,50.00,0.0,0.160
"Vitamin A, IU",5078.00,0.00,98.000000,0.000,0.00,397.00,0.00,0.00,64.000000,600.00,1724.000,0.000,0.000,0.00,0.00,0.0,0.000
"Vitamin C, total ascorbic acid",11.70,0.00,36.600000,2.800,24.70,5.70,0.00,0.00,8.700000,0.00,20.700,3.500,0.000,0.00,0.00,0.0,3.200
"Vitamin D (D2 + D3), International Units",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,138.000,154.000,0.000,0.00,0.00,0.0,0.000
10:0,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.001000,0.00,0.000,0.021,0.000,0.00,0.00,0.0,0.000
12:0,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.002000,0.00,0.000,0.012,0.000,0.00,0.00,0.0,0.000
14:0,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.002000,0.00,0.000,0.020,0.007,0.00,0.00,0.0,0.002
14:1,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
15:0,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
15:1,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
16:0,0.00,0.00,0.034000,0.016,0.00,0.00,0.00,0.00,0.102000,0.00,0.000,0.122,0.294,0.00,0.00,0.0,0.010
16:1,0.00,0.00,0.000000,0.001,0.00,0.00,0.00,0.00,0.010000,0.00,0.000,0.089,0.004,0.00,0.00,0.0,0.000
17:0,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
17:1,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
18:0,0.00,0.00,0.000000,0.002,0.00,0.00,0.00,0.00,0.005000,0.00,0.000,0.051,0.022,0.00,0.00,0.0,0.002
18:1,0.00,0.00,0.017000,0.004,0.00,0.00,0.00,0.00,0.022000,0.00,0.000,0.151,0.371,0.00,0.00,0.0,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Theobromine,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Thiamin,0.00,0.00,0.061000,0.041,0.00,0.00,0.00,0.00,0.031000,0.00,1.000,0.300,0.118,0.00,0.00,0.0,0.031
Threonine,0.00,0.00,0.035000,0.000,0.00,0.00,0.00,0.00,0.028000,0.00,0.000,0.497,0.000,0.00,0.00,0.0,0.000
"Tocopherol, beta",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
"Tocopherol, delta",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.010000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
"Tocopherol, gamma",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.020000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
"Tocotrienol, alpha",0.00,0.00,0.040000,0.000,0.00,0.00,0.00,0.00,0.060000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
"Tocotrienol, beta",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
"Tocotrienol, gamma",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Tryptophan,0.00,0.00,0.011000,0.000,0.00,0.00,0.00,0.00,0.009000,0.00,0.000,0.031,0.000,0.00,0.00,0.0,0.000
Tyrosine,0.00,0.00,0.019000,0.000,0.00,0.00,0.00,0.00,0.009000,0.00,0.000,0.323,0.000,0.00,0.00,0.0,0.000
Valine,0.00,0.00,0.042000,0.000,0.00,0.00,0.00,0.00,0.047000,0.00,0.000,0.486,0.000,0.00,0.00,0.0,0.000
"Vitamin A, RAE",0.00,0.00,5.000000,25.000,0.00,0.00,0.00,0.00,3.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,4.000
Vitamin B-12,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,5.170,0.000,0.000,0.00,0.00,0.0,0.000
"Vitamin B-12, added",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Vitamin B-6,0.00,0.00,0.124000,0.042,0.00,0.00,0.00,0.00,0.367000,0.00,1.724,0.965,0.371,0.00,0.00,0.0,0.051
Vitamin D (D2 + D3),0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,3.900,0.000,0.00,0.00,0.0,0.000
Vitamin E (alpha-tocopherol),0.00,0.00,0.150000,0.180,0.00,0.00,0.00,0.00,0.100000,0.00,0.000,0.000,0.090,0.00,0.00,0.0,0.030
"Vitamin E, added",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Vitamin K (Dihydrophylloquinone),0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Vitamin K (phylloquinone),0.00,0.00,76.000000,24.100,0.00,0.00,0.00,0.00,0.500000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,7.200
Vitamins and Other Components,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Water,0.00,0.00,92.180000,95.640,0.00,0.00,0.00,0.00,74.910000,0.00,0.000,9.500,19.850,0.00,0.00,0.0,96.730
"Zinc, Zn",0.00,0.00,0.180000,0.150,0.00,0.00,0.00,0.00,0.150000,0.00,0.000,7.660,0.690,0.00,0.00,0.0,0.170
"Tocotrienol, delta",0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Beta-sitosterol,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Campesterol,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,20.000,0.000,0.00,0.00,0.0,0.000
Stigmasterol,0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000
Vitamin D2 (ergocalciferol),0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,3.900,0.000,0.00,0.00,0.0,0.000
Vitamin D3 (cholecalciferol),0.00,0.00,0.000000,0.000,0.00,0.00,0.00,0.00,0.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,0.000

In [7]:
#export.to_csv('total_table.csv', index = False)

# Prices & Google Sheets

In [8]:
SHEETs = [# Stigler's foods, modern prices
          ("1-SnIIK7ZxtXVvCJUYK9ory2fFhRCICWOQ1NJVNkPb4k","Sheet1"), 
         ]

In [9]:
#Food Price Data
import warnings

DFs = []
#for csv in CSVs:  # Uncomment to use a list of csv files as inputs
#  DFs.append(pd.read_csv(csv,dtype=str))

try:
    if len(SHEETs):
        for ID, RANGE_NAME in SHEETs:
            try:
                if "docs.google.com" in ID:
                    sheet = "%s&output=csv" % ID
                else:
                    sheet = "https://docs.google.com/spreadsheet/ccc?key=%s&output=csv" % ID
                DFs.append(pd.read_csv(sheet))
            except ParserError:
                warnings.warn("Can't read sheet at https://docs.google.com/spreadsheets/d/%s.\nCheck Sharing settings, so that anyone with link can view?" % ID)
except NameError: # SHEETS not defined?
    pass

df = pd.concat(DFs,ignore_index=True,sort=False)
# Some columns which ought to be numeric are actually str; convert them
df['Price'] = df['Price'].astype(float)
df['Quantity'] = df['Quantity'].astype(float)
df['FDC'] = df['FDC'].astype(int)

df
pricing = df
pricing

              Food  Quantity Units   Price Date       Location     FDC
0   Collard Greens       1.0   lbs   0.860  3/2  Berkeley Bowl  380297
1          Carrots       1.0   lbs   0.920  3/2  Berkeley Bowl  658616
2          Cabbage       1.0   lbs   0.990  3/2  Berkeley Bowl  169975
3          Lettuce       1.0   lbs   0.350  3/2  Berkeley Bowl  342618
4      Cauliflower       1.0   lbs   1.330  3/2  Berkeley Bowl  528384
5   Diced Tomatoes       1.0   lbs   0.380  3/2  Berkeley Bowl  371622
6             Rice       1.0   lbs   1.760  3/2  Berkeley Bowl  450892
7             Tofu       1.0   lbs   2.900  3/2  Berkeley Bowl  570267
8          Bananas       1.0   lbs   0.590  3/2  Berkeley Bowl  173944
9             Eggs       1.0   lbs   1.128  3/2  Berkeley Bowl  442160
10          Cereal       1.0   lbs   4.000  3/2  Berkeley Bowl  653426
11   Dried Shitake       1.0   lbs  15.000  3/2       Ranch 99  168436
12       Rice Wrap       1.0   lbs   5.940  3/2  Berkeley Bowl  340211
13         Noodles       1.0   lbs   4.330  3/2  Berkeley Bowl  373372
14   Peanut Butter       1.0   lbs   2.240  3/2  Berkeley Bowl  357668
15        Cilantro       1.0   lbs   0.780  3/2  Berkeley Bowl  530557
16       Cucumbers       1.0   lbs   1.490  3/2  Berkeley Bowl  342612

In [10]:
#Checking FDC Requirements
#The FDC database basically wants everything in either hundreds of grams (hectograms) or hundreds of milliliters (deciliters).
pricing['FDC Quantity'] = pricing[['Quantity','Units']].T.apply(lambda x : fdc.units(x['Quantity'],x['Units']))

# Now may want to filter df by time or place--need to get a unique set of food names.
pricing['FDC Price'] = pricing['Price']/pricing['FDC Quantity']

pricing.dropna(how='any') # Drop food with any missing data

# To use minimum price observed
Prices = pricing.groupby('Food',sort=False)['FDC Price'].min()

Prices

Food
Collard Greens    0.18959754547899468 / hectogram
Carrots           0.20282528121008736 / hectogram
Cabbage           0.21825763956302877 / hectogram
Lettuce           0.07716179176470714 / hectogram
Cauliflower        0.2932148087058872 / hectogram
Diced Tomatoes    0.08377565963025348 / hectogram
Rice               0.3880135814453845 / hectogram
Tofu               0.6393405603361448 / hectogram
Bananas           0.13007273468907776 / hectogram
Eggs              0.24868143174454185 / hectogram
Cereal             0.8818490487395102 / hectogram
Dried Shitake      3.3069339327731635 / hectogram
Rice Wrap          1.3095458373781728 / hectogram
Noodles            0.9546015952605198 / hectogram
Peanut Butter     0.49383546729412575 / hectogram
Cilantro           0.1719605645042045 / hectogram
Cucumbers         0.32848877065546755 / hectogram
Name: FDC Price, dtype: object

# Identify Constraints and Solve The Problem

In [11]:
# Choose sex/age group:
group = "F 19-30"

# Define *minimums*
bmin = pd.read_csv('./diet_minimums.csv').set_index('Nutrition')[group]

# Define *maximums*
bmax = pd.read_csv('./diet_maximums.csv').set_index('Nutrition')[group]

# Inspect:
bmin

Nutrition
Energy                            2000.0
Protein                             46.0
Fiber, total dietary                28.0
Folate, DFE                        400.0
Calcium, Ca                       1000.0
Carbohydrate, by difference        130.0
Iron, Fe                            18.0
Magnesium, Mg                      310.0
Niacin                              14.0
Phosphorus, P                      700.0
Potassium, K                      4700.0
Riboflavin                           1.1
Thiamin                              1.1
Vitamin A, RAE                     700.0
Vitamin B-12                         2.4
Vitamin B-6                          1.3
Vitamin C, total ascorbic acid      75.0
Vitamin E (alpha-tocopherol)        15.0
Vitamin K (phylloquinone)           90.0
Zinc, Zn                             8.0
Name: F 19-30, dtype: float64

In [12]:
c = Prices.apply(lambda x:x.magnitude).dropna()

# C is a list that is a compilation of what we have prices and nutritional info; shows list of ingredients and prices of amounts in Google Sheet

#use = list(set(c.index.tolist()).intersection(food_list))
#c = c[use]
c

Food
Collard Greens    0.189598
Carrots           0.202825
Cabbage           0.218258
Lettuce           0.077162
Cauliflower       0.293215
Diced Tomatoes    0.083776
Rice              0.388014
Tofu              0.639341
Bananas           0.130073
Eggs              0.248681
Cereal            0.881849
Dried Shitake     3.306934
Rice Wrap         1.309546
Noodles           0.954602
Peanut Butter     0.493835
Cilantro          0.171961
Cucumbers         0.328489
Name: FDC Price, dtype: float64

In [13]:
#D is nutritional info matrix
Aall = D

# Drop rows of A that we don't have constraints for.
Amin = Aall.loc[bmin.index]

Amax = Aall.loc[bmax.index]

# Minimum requirements involve multiplying constraint by -1 to make <=.
A = pd.concat([Amin,-Amax])

A

,Collard Greens,Carrots,Cabbage,Lettuce,Cauliflower,Diced Tomatoes,Rice,Tofu,Bananas,Eggs,Cereal,Dried Shitake,Rice Wrap,Noodles,Peanut Butter,Cilantro,Cucumbers
Nutrition,,,,,,,,,,,,,,,,,
Energy,16.00,38.00,24.617618,14.000,29.00,32.00,356.000,82.00,88.671226,140.00,379.000,1238.000,329.000,370.00,625.00,0.0,12.000
Protein,1.56,1.28,1.280000,0.900,1.18,0.79,6.670,10.59,1.090000,12.00,3.450,9.580,5.070,11.11,25.00,0.0,0.590
"Fiber, total dietary",1.60,3.80,2.500000,1.200,1.20,1.60,2.200,1.20,2.600000,0.00,3.400,11.500,2.100,3.70,6.20,0.0,0.700
"Folate, DFE",0.00,0.00,43.000000,29.000,0.00,0.00,0.000,0.00,20.000000,0.00,0.000,163.000,4.000,0.00,0.00,0.0,14.000
"Calcium, Ca",78.00,38.00,40.000000,18.000,0.00,16.00,44.000,118.00,5.000000,40.00,0.000,11.000,10.000,0.00,0.00,0.0,14.000
"Carbohydrate, by difference",3.12,11.54,5.800000,2.970,4.71,7.14,80.000,3.53,22.840000,0.00,89.660,75.370,72.540,77.78,21.88,0.0,2.160
"Iron, Fe",0.84,1.28,0.470000,0.410,0.00,0.29,4.000,3.39,0.260000,1.44,15.520,1.720,0.380,1.33,2.25,0.0,0.220
"Magnesium, Mg",0.00,0.00,12.000000,7.000,0.00,0.00,0.000,0.00,27.000000,0.00,0.000,132.000,30.000,0.00,0.00,0.0,12.000
Niacin,0.00,0.00,0.234000,0.123,0.00,0.00,4.444,0.00,0.665000,0.00,17.241,14.100,2.202,0.00,0.00,0.0,0.037
"Phosphorus, P",0.00,0.00,26.000000,20.000,0.00,0.00,0.000,0.00,22.000000,0.00,0.000,294.000,84.000,0.00,0.00,0.0,21.000
"Potassium, K",74.00,256.00,170.000000,141.000,0.00,119.00,0.000,0.00,358.000000,0.00,121.000,1534.000,65.000,148.00,0.00,0.0,136.000
Riboflavin,0.00,0.00,0.040000,0.025,0.00,0.00,0.000,0.00,0.073000,0.00,1.466,1.270,0.018,0.00,0.00,0.0,0.025
Thiamin,0.00,0.00,0.061000,0.041,0.00,0.00,0.000,0.00,0.031000,0.00,1.000,0.300,0.118,0.00,0.00,0.0,0.031
"Vitamin A, RAE",0.00,0.00,5.000000,25.000,0.00,0.00,0.000,0.00,3.000000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,4.000
Vitamin B-12,0.00,0.00,0.000000,0.000,0.00,0.00,0.000,0.00,0.000000,0.00,5.170,0.000,0.000,0.00,0.00,0.0,0.000
Vitamin B-6,0.00,0.00,0.124000,0.042,0.00,0.00,0.000,0.00,0.367000,0.00,1.724,0.965,0.371,0.00,0.00,0.0,0.051
"Vitamin C, total ascorbic acid",11.70,0.00,36.600000,2.800,24.70,5.70,0.000,0.00,8.700000,0.00,20.700,3.500,0.000,0.00,0.00,0.0,3.200
Vitamin E (alpha-tocopherol),0.00,0.00,0.150000,0.180,0.00,0.00,0.000,0.00,0.100000,0.00,0.000,0.000,0.090,0.00,0.00,0.0,0.030
Vitamin K (phylloquinone),0.00,0.00,76.000000,24.100,0.00,0.00,0.000,0.00,0.500000,0.00,0.000,0.000,0.000,0.00,0.00,0.0,7.200
"Zinc, Zn",0.00,0.00,0.180000,0.150,0.00,0.00,0.000,0.00,0.150000,0.00,0.000,7.660,0.690,0.00,0.00,0.0,0.170
"Sodium, Na",-12.00,-64.00,-18.000000,-10.000,-29.00,-183.00,-0.000,-9.00,-1.000000,-140.00,-517.000,-13.000,-310.000,-352.00,-469.00,-0.0,-2.000

In [14]:
#Modifying Constraints to fit Stigler's constraints

b = pd.DataFrame(pd.concat([bmin,-bmax])) # Note sign change for max constraints
listb = ['Protein', 'Carbohydrate, by difference', 'Fiber, total dietary', 'Calcium, Ca', 'Iron, Fe', 'Vitamin A', 'Thiamin', 'Riboflavin', 'Niacin']
drop_list = ['Energy', 'Folate, DFE', 'Magnesium, Mg', 'Phosphorus, P', 'Potassium, K', 'Vitamin B-12', 'Vitamin B-6', 'Vitamin C, total ascorbic acid', 'Vitamin E (alpha-tocopherol)','Vitamin K (phylloquinone)', 'Zinc, Zn', 'Sodium, Na']

b = b.drop(drop_list)
A = A.drop(drop_list)

In [15]:
#SOLVE THE PROBLEM

from  scipy.optimize import linprog as lp
import numpy as np

tol = 1e-6 # Numbers in solution smaller than this (in absolute value) treated as zeros

# Now solve problem!  (Note that the linear program solver we'll use assumes
# "less-than-or-equal" constraints.  We can switch back and forth by
# multiplying $A$ and $b$ by $-1$.)

result = lp(c, -A, -b, method='interior-point')

result

     con: array([], dtype=float64)
     fun: 4.008183342374733
 message: 'Optimization terminated successfully.'
     nit: 10
   slack: array([2.10365414e-09, 1.82409303e+01, 1.67713097e-08, 1.00158077e+02,
       7.90791975e+00, 1.07928955e-09, 1.23452712e-08, 3.20851305e-01,
       2.57454644e-07])
  status: 0
 success: True
       x: array([5.51019977e+00, 2.58446602e-10, 2.20705626e-10, 2.80000000e+01,
       7.30714981e-11, 8.84546611e-10, 1.31678008e+00, 8.35005062e-11,
       3.80570953e-10, 2.06652352e-01, 2.72851304e-01, 8.19567639e-12,
       1.82268138e-11, 2.73520901e-11, 1.52370333e-10, 0.00000000e+00,
       7.11832101e-11])

# Results

## Minimum Cost

In [22]:
print("Cost of diet for %s is $%4.2f per day." % (group,result.fun))

Cost of diet for F 19-30 is $4.01 per day.

## Suggested Diet

In [23]:
#DIET CONSISTS OF...
# Put back into nice series
diet = pd.DataFrame(result.x,index=c.index)

print("\nYou'll be eating (in 100s of grams or milliliters):")
print(diet[diet >= tol])  # Drop items with quantities less than precision of calculation.

You'll be eating (in 100s of grams or milliliters):
                        0
Food
Collard Greens   5.510200
Carrots               NaN
Cabbage               NaN
Lettuce         28.000000
Cauliflower           NaN
Diced Tomatoes        NaN
Rice             1.316780
Tofu                  NaN
Bananas               NaN
Eggs             0.206652
Cereal           0.272851
Dried Shitake         NaN
Rice Wrap             NaN
Noodles               NaN
Peanut Butter         NaN
Cilantro              NaN
Cucumbers             NaN

## Total Nutrition Possible from ingredients

In [25]:
A.T.sum()

Nutrition
Protein                         92.140
Fiber, total dietary            45.500
Calcium, Ca                    432.000
Carbohydrate, by difference    481.040
Iron, Fe                        33.800
Niacin                          39.046
Riboflavin                       2.917
Thiamin                          1.582
Vitamin A, RAE                  37.000
dtype: float64

## Our Outcome vs. Recommended

In [27]:
A.shape, diet.shape
A.columns == diet.index
O =A.dot(diet)
E = np.abs(b)
tab = O.merge(E, on = 'Nutrition')
tab = tab.rename(columns = {0: 'Outcome', 'F 19-30': 'Recommended'})
tab

                                 Outcome  Recommended
Nutrition
Protein                        46.000000         46.0
Fiber, total dietary           46.240930         28.0
Calcium, Ca                  1000.000000       1000.0
Carbohydrate, by difference   230.158077        130.0
Iron, Fe                       25.907920         18.0
Niacin                         14.000000         14.0
Riboflavin                      1.100000          1.1
Thiamin                         1.420851          1.1
Vitamin A, RAE                700.000000        700.0

## Constraining Nutrients

In [28]:
print("\nConstraining nutrients are:")
excess = tab.diff(axis=1).iloc[:,1]
print(excess.loc[np.abs(excess) < tol].index.tolist())

Constraining nutrients are:
['Protein', 'Calcium, Ca', 'Niacin', 'Riboflavin', 'Vitamin A, RAE']